// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBARC6XwB54J2YVyi0eH5Zk9QUC5QCbfjQ',
    appId: '1:854503433698:android:cd512384766b15322845bb',
    messagingSenderId: '854503433698',
    projectId: 'fortnite-top',
    databaseURL: 'https://fortnite-top-default-rtdb.firebaseio.com',
    storageBucket: 'fortnite-top.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHe5R2Sp9i4aIGBtwgKcfbHHtMJP2uMsQ',
    appId: '1:854503433698:web:f683a2f4e51964a32845bb',
    messagingSenderId: '854503433698',
    projectId: 'fortnite-top',
    authDomain: 'fortnite-top.firebaseapp.com',
    databaseURL: 'https://fortnite-top-default-rtdb.firebaseio.com',
    storageBucket: 'fortnite-top.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdT2Rp0fW003zbsqyBC8wy7dlnaMmBLQs',
    appId: '1:854503433698:ios:f0433219996cabf52845bb',
    messagingSenderId: '854503433698',
    projectId: 'fortnite-top',
    storageBucket: 'fortnite-top.firebasestorage.app',
    iosBundleId: 'com.example.leilaoFortTop',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdT2Rp0fW003zbsqyBC8wy7dlnaMmBLQs',
    appId: '1:854503433698:ios:f0433219996cabf52845bb',
    messagingSenderId: '854503433698',
    projectId: 'fortnite-top',
    storageBucket: 'fortnite-top.firebasestorage.app',
    iosBundleId: 'com.example.leilaoFortTop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHe5R2Sp9i4aIGBtwgKcfbHHtMJP2uMsQ',
    appId: '1:854503433698:web:25be7b24ca58d1312845bb',
    messagingSenderId: '854503433698',
    projectId: 'fortnite-top',
    authDomain: 'fortnite-top.firebaseapp.com',
    databaseURL: 'https://fortnite-top-default-rtdb.firebaseio.com',
    storageBucket: 'fortnite-top.firebasestorage.app',
  );

}